/*Trang chủ*/
/**/
/*lấy tên các món ăn hot*/
Select FOOD_NAME
From FOOD
Where IS_HOT LIKE 'HOT'
/*lấy giá các món ăn hot*/
SELECT FOOD_NAME,LISTED_PRICE AS GIABAN
FROM FOOD
WHERE IS_HOT LIKE 'HOT'
/*lấy link ảnh món ăn hot*/
SELECT FOOD_NAME,L_IMG
FROM FOOD
WHERE IS_HOT LIKE 'HOT'
/*lấy tên món ăn là combo*/
SELECT FOOD_NAME 
FROM FOOD
WHERE IS_COMBO = 1
/*lấy link ảnh món ăn là combo*/
SELECT FOOD_NAME ,L_IMG
FROM FOOD
WHERE IS_COMBO = 1
/*lấy món ăn giảm giá*/
SELECT FOOD_NAME
FROM FOOD INNER JOIN SALE_DETAIL ON FOOD.ID_SALE = SALE_DETAIL.ID_SALE
WHERE SALE_DETAIL.TYPE_SALE LIKE 'GIAMGIA'
/*lấy link ảnh món ăn giảm giá*/
SELECT FOOD_NAME , L_IMG AS ANH
FROM FOOD INNER JOIN SALE_DETAIL ON FOOD.ID_SALE = SALE_DETAIL.ID_SALE
WHERE SALE_DETAIL.TYPE_SALE LIKE 'GIAMGIA'
/*lấy số tiền giảm ảnh món ăn giảm giá*/
SELECT FOOD.FOOD_NAME AS TEN, FOOD.LISTED_PRICE * SALE_DETAIL.VALUESS AS TIEN_GIAM
FROM FOOD INNER JOIN SALE_DETAIL ON FOOD.ID_SALE = SALE_DETAIL.ID_SALE
WHERE SALE_DETAIL.TYPE_SALE LIKE 'GIAMGIA'
/*gian hang*/
/**/
/*lấy tên sản phẩm theo loại món ăn*/
SELECT FOOD_NAME
FROM FOOD
WHERE TYPE_FOOD = 'CƠM GÀ'

/*lấy giá sản phẩm theo loại*/
SELECT FOOD.LISTED_PRICE
FROM FOOD
WHERE TYPE_FOOD = 'CƠM GÀ'

/*lấy hình ảnh theo loại món ăn cần tìm*/
SELECT FOOD_NAME, L_IMG AS LINK_ANH
FROM FOOD
WHERE TYPE_FOOD = 'CƠM GÀ'

/*thanh toán*/
SELECT USER_NAMES
FROM ACCOUNT INNER JOIN USER_INFORMATION ON ACCOUNT.ID_USER = USER_INFORMATION.ID_USER

/*YEU THICH TRONG USER*/
SELECT FOOD.FOOD_NAME AS FAVOURITE_FOOD,FOOD.LISTED_PRICE ,ACCOUNT.AVATAR AS LINK_AVT
FROM ACCOUNT INNER JOIN  (FAVOURITE INNER JOIN FOOD ON FAVOURITE.ID_FOOD = FOOD.ID_FOOD ) 
ON ACCOUNT.ID_ACCOUNT = FAVOURITE.ID_ACCOUNT

/*VOUCHER TRONG USER*/
SELECT *
FROM ACCOUNT INNER JOIN (VOUCHER_LIST INNER JOIN VOUCHER ON VOUCHER_LIST.ID_VOUCHER = VOUCHER.ID_VOUCHER
) ON ACCOUNT.ID_ACCOUNT = VOUCHER_LIST.
/*DOANH SO*/

SELECT SUM(PRICE) AS THANHTIEN, ID_ORDER
FROM ORDER_DETAILS
GROUP BY ID_ORDER 

SELECT COUNT(ID_ORDER) AS SL_ORDER
FROM ORDER_DETAILS

SELECT COUNT(ID_ORDER) AS SL_DA_GIAO
FROM ORDER_DETAILS
WHERE ORDER_DETAILS.STATUSS LIKE 'ĐÃ GIAO'

SELECT COUNT(ORDERS.ID_ORDER) AS SL_DAT, FOOD.TYPE_FOOD
FROM ORDERS INNER JOIN (ORDER_DETAILS INNER JOIN FOOD ON ORDER_DETAILS.ID_FOOD = FOOD.ID_FOOD) ON ORDERS.ID_ORDER
= ORDER_DETAILS.ID_ORDER
GROUP BY FOOD.TYPE_FOOD,FOOD.ID_SIZE
HAVING FOOD.TYPE_FOOD LIKE'CƠM GÀ' AND FOOD.ID_SIZE LIKE'SIZE1'







